## NumPy

NumPy is a Linear Algebra Library for Python. 

### Using NumPy
To use numpy you must import it as a library:


In [1]:
import numpy as np


In [2]:
my_list = [1,2,3,4,5,6,7,8,9,10]

In [3]:
my_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
np.array(my_list)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

##### arange
Return evenly spaced values within a given interval

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

##### zeros and ones
Generate arrays of zeros or ones

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [16]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [17]:
np.ones(3)

array([ 1.,  1.,  1.])

In [18]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

##### linspace
Return evenly spaced numbers over a specified interval.

In [19]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [20]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

##### eye
Creates an identity matrix

In [21]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Random
Numpy also has lots of ways to create random number arrays:

##### rand
Create an array of a given shape and populate it with random samples from a uniform distribution over [0,1].

In [22]:
np.random.rand(2)

array([ 0.83736942,  0.66867093])

In [25]:
np.random.rand(10)*5

array([ 0.10557067,  3.44458664,  0.07209798,  2.41424158,  2.12989503,
        2.17438854,  1.99717223,  4.96485719,  2.06479333,  2.3336915 ])

In [26]:
np.random.rand(5,5)

array([[ 0.70507509,  0.32928918,  0.48105149,  0.78403427,  0.89757095],
       [ 0.8423513 ,  0.68560646,  0.06710582,  0.13161088,  0.07877949],
       [ 0.15801452,  0.32378424,  0.11137993,  0.51578514,  0.49725506],
       [ 0.507273  ,  0.45481941,  0.62331855,  0.53913933,  0.15445382],
       [ 0.92061488,  0.09356053,  0.69941967,  0.83601964,  0.27825356]])

##### randn
Returns a sample (or samples) from the "standard normal" distribution. Unlike rand with returns uniform:

In [27]:
np.random.randn(5)

array([ 0.11876922, -0.25543563,  1.0190672 ,  0.39953084, -1.25669128])

In [28]:
np.random.randn(5,5)

array([[-1.14019182,  1.65300136, -2.06480361,  0.40362704,  0.23601216],
       [ 0.13109795, -0.13027291, -0.58523438, -2.16169461,  0.03346584],
       [ 0.58556031,  0.0811076 , -0.32088578, -0.53640215,  0.34249934],
       [-0.32317247,  3.46677691, -1.06937086, -1.31627705, -0.92332535],
       [ 1.05758744,  1.33352764,  2.06506563, -1.47653944,  1.36949763]])

##### randint
Return random integers from low(inclusive) to high(exclusive).

In [31]:
np.random.randint(1,100)

59

In [32]:
np.random.randint(1,100,25)

array([69, 42, 99, 94, 47, 50, 25, 99, 96, 86, 64, 88, 55, 76,  4,  1, 86,
        9, 86, 39, 53, 76,  5, 45, 92])

### Array Attributes and Methods
Some useful attributes and methods of an array:

In [33]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [34]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
ranarr

array([47,  1,  5, 29, 12, 23, 18, 23, 33, 13])

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.shape

(25,)

In [38]:
arr2 = arr.reshape(5,5)

In [39]:
arr2.shape

(5, 5)

In [40]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

##### max, min, argmax, argmin
These are useful methods for finding man or min values. Or to find their index locations using argmax or argmin.

In [42]:
ranarr

array([47,  1,  5, 29, 12, 23, 18, 23, 33, 13])

In [43]:
ranarr.max()

47

In [44]:
ranarr.min()

1

In [45]:
ranarr.argmax()

0

In [46]:
ranarr.argmin()

1

In [49]:
 ran2 = ranarr.reshape(2,5)

In [50]:
ran2.min()

1

In [54]:
ran2.argmin()

0

In [52]:
ran2


array([[47,  1,  5, 29, 12],
       [23, 18, 23, 33, 13]])

In [53]:
ranarr

array([47,  1,  5, 29, 12, 23, 18, 23, 33, 13])

##### dtype
You can also grab the data type of the object in the array:

In [55]:
arr.dtype

dtype('int32')

In [56]:
arr[2:4]

array([2, 3])

In [57]:
arr[-4:]

array([21, 22, 23, 24])

In [58]:
arr[20]

20

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])